import { formatAcademicDate, formatWatTime } from '../utils/date.js';
import { useEffect, useState } from 'react';
import { CalendarCheck2, CheckCircle2, CircleX, Clock3, Fingerprint, RefreshCw, ShieldCheck } from 'lucide-react';
import { useAuth } from '../features/auth/useAuth.js';
import { attendanceApi } from '../features/attendance/attendance.api.js';

export function AttendancePage() {
  const { token, logout } = useAuth(); const [data, setData] = useState(null); const [error, setError] = useState(''); const [revision, setRevision] = useState(0);
  useEffect(() => { const controller = new AbortController(); Promise.all([attendanceApi.summary(token, controller.signal), attendanceApi.my(token, controller.signal)]).then(([summary, attendance]) => setData({ ...summary, ...attendance })).catch((failure) => { if (!controller.signal.aborted) { if (failure.status === 401) logout(); else setError(failure.message); } }); return () => controller.abort(); }, [token, logout, revision]);
  return <section className="attendance-workspace"><header className="attendance-heading page-banner"><div><h1>Attendance</h1><p>Official records from your closed class sessions.</p></div><button className="secondary" onClick={() => { setError(''); setRevision((value) => value + 1); }}><RefreshCw size={16} aria-hidden="true" />Refresh</button></header>
    {error ? <p role="alert">{error}</p> : !data ? <p role="status">Loading attendance…</p> : <div className="attendance-layout"><section className="attendance-standing"><header><div><Fingerprint size={19} aria-hidden="true" /><h2>Course standing</h2></div><span>Closed sessions only</span></header>{data.summaries.length ? <ul>{data.summaries.map((item) => <li key={item.courseId}><div><strong>{item.courseCode}</strong><span>{item.attendedSessions} of {item.eligibleSessions} closed sessions</span><span className="attendance-rule" role="progressbar" aria-label={`${item.courseCode} attendance`} aria-valuemin="0" aria-valuemax="100" aria-valuenow={item.percentage}><i style={{ width: `${item.percentage}%` }} /></span></div><b>{item.percentage}%</b></li>)}</ul> : <div className="attendance-empty"><ShieldCheck size={23} aria-hidden="true" /><div><h2>No closed attendance sessions yet.</h2><p>Your official record appears after a lecturer closes a class session.</p></div></div>}<aside className="attendance-record-note"><ShieldCheck size={18} aria-hidden="true" /><p><strong>Official record.</strong> Attendance percentages are calculated only after a lecturer closes a session.</p></aside></section><section className="attendance-history"><header><div><CalendarCheck2 size={19} aria-hidden="true" /><h2>Session history</h2></div><span>{data.attendance.length} {data.attendance.length === 1 ? 'session' : 'sessions'}</span></header>{data.attendance.length ? <ul>{data.attendance.map((item) => { const present = Boolean(item.recordedAt); const active = !present && item.status === 'ACTIVE'; const label = present ? `Present · ${formatWatTime(item.recordedAt)} WAT` : active ? 'Session active' : 'Absent'; return <li key={item.sessionId}><span className={`attendance-history-icon${present ? ' is-present' : active ? ' is-active' : ' is-absent'}`}>{present ? <CheckCircle2 size={19} aria-hidden="true" /> : active ? <Clock3 size={19} aria-hidden="true" /> : <CircleX size={19} aria-hidden="true" />}</span><div><strong>{item.courseCode}</strong><time>{formatAcademicDate(item.openedAt)}</time></div><span className={`attendance-history-state${present ? ' is-present' : active ? ' is-active' : ' is-absent'}`}>{label}</span></li>; })}</ul> : <div className="attendance-empty"><CalendarCheck2 size={23} aria-hidden="true" /><div><h2>No sessions to show.</h2><p>Attendance sessions will appear here when your courses begin.</p></div></div>}</section></div>}
  </section>;
}
